config/routes.rb
Rails.application.routes.draw do
  resources :homes

  root 'homes#index'

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
  end

  # GET /homes/1
  # GET /homes/1.json
  def show
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<h1>Editing Home</h1>

<%= render 'form' %>

<%= link_to 'Show', @home %> |
<%= link_to 'Back', homes_path %>

app/views/homes/new.html.erb
<h1>New Home</h1>

<%= render 'form' %>

<%= link_to 'Back', homes_path %>

app/views/homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @home.description %>
</p>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jnilan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target="#navbar" data-offset="0">
    <header id="header" role="banner">
        <div class="container">
            <div id="navbar" class="navbar navbar-default">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <%= link_to 'Joe Nilan', root_path, class: 'navbar-brand' %>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="#main-slider"><i class="glyphicon glyphicon-home"></i></a></li>

 						<li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Code <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Bitbucket', 'http://bitbucket.com/joenilan', :target => "_blank" %></li>
            <li><%= link_to 'Github', 'http://github.com/joenilan', :target => "_blank" %></li>
            <!-- <li role="separator" class="divider"></li>-->
          </ul>
        </li>
                        <li><a href="#services">Skills</a></li>
                        <li><a href="#portfolio">Portfolio</a></li>
                        <li><a href="#resume">Resume</a></li>
                        <!-- <li><a href="#pricing">Pricing</a></li> -->
                        <li><a href="#about-us">About Me</a></li>
                        <li><a href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header><!--/#header-->
<div class="container">
	<div class="yield">
    	<%= yield %>
    </div>
</div>
    <footer id="footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    &copy; 2015 <a target="_blank" href="http://jnilan.herokuapp.com/" title=""> Joseph Nilan</a>. All Rights Reserved.
                </div>

            </div>
        </div>
    </footer>
</html>